### ISSUE TITLE
(URGENT) Unable to fetch ISO/IEC DIR 2

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-iec#37]
````
relaton fetch "ISO/IEC DIR 2" --type ISO
[relaton] cache /Users/nickn/.relaton/cache/cache/: version is obsolete and cache is cleared.
[relaton-iec] ("ISO/IEC DIR 2") fetching...
Traceback (most recent call last):
	19: from /Users/nickn/.rvm/gems/ruby-2.7.2/bin/relaton:23:in `<main>'
	18: from /Users/nickn/.rvm/gems/ruby-2.7.2/bin/relaton:23:in `load'
	17: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-cli-1.7.1/exe/relaton:20:in `<top (required)>'
	16: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-cli-1.7.1/lib/relaton/cli.rb:21:in `start'
	15: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	14: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	13: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	12: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	11: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-cli-1.7.1/lib/relaton/cli/command.rb:21:in `fetch'
	10: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-cli-1.7.1/lib/relaton/cli/command.rb:151:in `fetch_document'
	 9: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-1.7.4/lib/relaton/db.rb:60:in `fetch'
	 8: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-1.7.4/lib/relaton/db.rb:348:in `check_bibliocache'
	 7: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-1.7.4/lib/relaton/db.rb:366:in `new_bib_entry'
	 6: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-1.7.4/lib/relaton/db.rb:380:in `net_retry'
	 5: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-iso-1.7.2/lib/relaton_iso/processor.rb:19:in `get'
	 4: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-iso-1.7.2/lib/relaton_iso/iso_bibliography.rb:53:in `get'
	 3: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-iec-1.7.6/lib/relaton_iec/iec_bibliography.rb:46:in `get'
	 2: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-iec-1.7.6/lib/relaton_iec/iec_bibliography.rb:207:in `iecbib_get'
	 1: from /Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-iec-1.7.6/lib/relaton_iec/iec_bibliography.rb:168:in `results_filter'
/Users/nickn/.rvm/gems/ruby-2.7.2/gems/relaton-iec-1.7.6/lib/relaton_iec/hit_collection.rb:28:in `to_all_parts': undefined local variable or method `lang' for #<RelatonIec::HitCollection:0x00007fcf2abf3168> (NameError)
````

**Comment by opoudjis** [comment]
It's turning out that even if I get rid of the unpopulated lang variable, the `@array` being processed in that routine for "ISO/IEC DIR 2" is empty anyway.

**Comment by andrew2net** [comment]
@opoudjis we have hardcoded the `ISO/IEC DIR*` references. There are 2 variants of the `ISO/IEC DIR 2` document: `ISO/IEC DIR 2 ISO` and `ISO/IEC DIR 2 IEC`. So it's necessary to use one of these references.
